[package]
name = "mandelbrot-rust-generator"
version = "0.1.0"
authors = ["Daniel Florescu <daniel.florescu1905@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16.6"
num = "0.3"